service: siksha-crawler
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-2
  timeout: 60
  role: arn:aws:iam::405906814034:role/siksha-lambda-role

  # version upgrade 필요
  # https://www.serverless.com/framework/docs/guides/upgrading-v3
  lambdaHashingVersion: 20201221

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    # linux 이외의 환경에서 배포할 시 non-linux(docker 필요함) / linux 에서 배포라면 false
    dockerizePip: non-linux

functions:
  crawler:
    handler: handler.crawl
    timeout: 60
    environment:
      DB_HOST: ${ssm:/siksha/DB_HOST}
      DB_NAME: ${ssm:/siksha/DB_NAME}
      DB_USER: ${ssm:/siksha/DB_USER}
      DB_PASSWORD: ${ssm:/siksha/DB_PASSWORD}
      SLACK_TOKEN: ${ssm:/siksha/SLACK_TOKEN}
      SLACK_CHANNEL: ${ssm:/siksha/SLACK_CHANNEL}
    events:
      # UTC 20:00 -> KST 05:00
      # 매일 오전 5시에 크롤링
      - schedule: cron(0 20 * * ? *)
  crawler-dev:
    handler: handler.crawl
    timeout: 60
    environment:
      DB_HOST: ${ssm:/siksha/DB_HOST}
      DB_NAME: ${ssm:/siksha/DB_NAME_DEV}
      DB_USER: ${ssm:/siksha/DB_USER_DEV}
      DB_PASSWORD: ${ssm:/siksha/DB_PASSWORD_DEV}
      SLACK_TOKEN: ${ssm:/siksha/SLACK_TOKEN}
      SLACK_CHANNEL: ${ssm:/siksha/SLACK_CHANNEL}
    events:
      # UTC 20:00 -> KST 05:00
      # 매주 월요일 오전 5시에 크롤링
      - schedule: cron(0 20 * * 2 *)

