service: siksha-crawler
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-2
  timeout: 60
  role: arn:aws:iam::405906814034:role/siksha-lambda-role
  lambdaHashingVersion: 20201221

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    # linux 이외의 환경에서 배포할 시 non-linux(docker 필요함) / linux 에서 배포라면 false
    dockerizePip: non-linux

functions:
  crawler:
    handler: handler.crawl
    timeout: 60
    environment:
      DB_HOST: siksha.caxwrw8c4qqq.ap-northeast-2.rds.amazonaws.com
      DB_NAME: siksha
      DB_USER: admin
      DB_PASSWORD: up57SLEWmT
      SLACK_TOKEN: xoxb-6971793892-1687810242630-Cj67mtdVLv8gP9s8Qg1uEwLM
      SLACK_CHANNEL: C01L7PG8CEA
    events:
      # UTC 20:00 -> KST 05:00
      # 매일 오전 5시에 크롤링
      - schedule: cron(0 20 * * ? *)
