name: Deploy-dev-crawler

on:
  push:
    branches: ["dev"]

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      ocir_repository: siksha-dev/siksha-crawler
      dockerfile: Dockerfile
      gitops_overlay_path: argocd/siksha-dev
    secrets:
      OCI_AUTH_TOKEN: ${{ secrets.OCI_AUTH_TOKEN }}
      DB_HOST: ${{ secrets.DB_HOST_DEV }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME_DEV }}
      DB_USER: ${{ secrets.DB_USER_DEV }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD_DEV }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_DEV }}
      DEPLOYER_APP_PRIVATE_KEY: ${{ secrets.DEPLOYER_APP_PRIVATE_KEY }}
