name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: use python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: install ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.13.0
      - name: check if code linted
        run: |
          ruff check $(git ls-files '*.py')
          ruff format --check $(git ls-files '*.py')
