name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: use python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: install black, pylint
        run: poetry install --only dev
      - name: check if code linted
        run: |
          poetry run black --check $(git ls-files '*.py')
          poetry run pylint --recursive=yes $(git ls-files '*.py') || true
