name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install poetry
        run: pipx install poetry
      - name: use python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
          cache: poetry
      - name: install black, pylint
        run: poetry install --only dev
      - name: check if code linted
        run: |
          poetry run black --check $(git ls-files '*.py')
          poetry run pylint --recursive=yes $(git ls-files '*.py') || true
