name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: use python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "6.6.1"
      - name: install dependencies
        run: uv sync --group dev
      - name: check if code linted
        run: |
          uv run ruff check $(git ls-files '*.py')
          uv run ruff format --check $(git ls-files '*.py')
