name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: use python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: install black, pylint
        run: |
          python -m pip install --upgrade pip
          pip install black==23.3.0 pylint==2.17.4
      - name: check if code linted
        run: |
          black --check $(git ls-files '*.py')
          pylint --recursive=yes $(git ls-files '*.py') || true
